# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb749bedee2bf4b0104c24ad7c1ad2591ca608bfeedca62fc50125379248342990c6f0b425e56fe41931b55681d078fe39c34e8ee7ae613914284029d0081a5c

test:
  secret_key_base: 5c7e8893522b881357f57f72e285db1fb154f1e84bad47a9d279dc0595b36e9775b5708c8da0a805b256f367ba75f8972b79261cce17d76ed1fe3895facfd6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
